config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registration: 'registration' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  root "users#profile"
  post "/registration", to: "users#registration"
  get "/profile", to: "users#profile"
  get "/confirm_gender", to: "users#confirm_gender"
  get "/update_gender", to: "users#update_gender"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :patronymic, presence: true

  # getting the gender of a new User after registration
  after_create :update_user_gender


  # getting User gender over API Dadata
  def get_gender(name)
    data = [name].to_json

    headers = {
        'Content-Type' => 'application/json',
        'Authorization' => "Token #{Rails.application.credentials.dadata[:API_key]}",
        'X-Secret' => "#{Rails.application.credentials.dadata[:secret_key]}"
    }

    res = HTTParty.post(
        'https://cleaner.dadata.ru/api/v1/clean/name',
        :body => data,
        :headers => headers
    )
    res[0]["gender"]
  end

  # getting full name of User from object
  def get_full_name(obj)
    @full_name = "#{obj.last_name} #{obj.first_name} #{obj.patronymic}"
  end

  # getting the User from the db after updating,
  # building his full name,
  # getting his gender and update User with gender
  def update_user_gender
    @current_date = DateTime.now
    full_name = get_full_name(self)
    gender = get_gender(full_name)
    confirmed_gender = self.confirmed_gender
    self.update({ gender: gender, confirmed_gender: confirmed_gender, gender_updated_at: @current_date })
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
require 'httparty'

class UsersController < ApplicationController
  def signup
    render plain: "OK"
  end

  def registration
    @user = User.new(sign_up_params)

    if @user.save
      redirect_to root_path
    else
      redirect_to root_path, :flash => { :alert => "Registration error!" }
    end
  end

  def profile
    @user = current_user
  end

  def confirm_gender
    @user = User.find(current_user.id)
    if @user.update(confirmed_gender: true)
      render json: {}, status: 200
    end
  end

  def update_gender
    if user_signed_in?
      @user = User.find(current_user.id)

      if @user.update_user_gender
        render json: { gender: @gender, status: "Пол (определён автоматически)" }, status: 200
      else
        render json: {}, status: 500
      end
    else
      redirect_to root_path, :flash => { :notice => "Nothing to run" }
    end
  end

  private

  def sign_up_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :patronymic,
                                 :gender,
                                 :email,
                                 :password,
                                 :password_confirmation
    )
  end

  def account_update_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :patronymic,
                                 :gender,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :current_password
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BafsyTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/profile.html.erb
<% if user_signed_in? %>
  <div class="container">
    <div class="col-md-8">
      <h1>Здравствуйте, <%= @user.first_name %></h1>
      <div class="card mb-3">
        <div class="card-body">

          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">Фамилия</h6>
            </div>

            <div class="col-sm-9 text-secondary">
              <%= @user.last_name %>
            </div>
          </div>
          <hr>

          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">Имя</h6>
            </div>
            <div class="col-sm-9 text-secondary">
              <%= @user.first_name %>
            </div>
          </div>
          <hr>

          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">Отчество</h6>
            </div>
            <div class="col-sm-9 text-secondary">
              <%= @user.patronymic %>
            </div>
          </div>
          <hr>

          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">Email</h6>
            </div>
            <div class="col-sm-9 text-secondary">
              <%= @user.email %>
            </div>
          </div>
          <hr>

          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0" id="status_gender">Пол
                <% if !@user.confirmed_gender %>
                  (определён автоматически)
                <% else %>
                  (подтвержден)
                <% end %>
              </h6>
            </div>
            <div class="col-sm-5 text-secondary" id="gender">
              <%= @user.gender %>
            </div>
            <div class="col-sm-4 text-secondary">
              <% if @user.confirmed_gender %>
                <%= link_to "Подтвердить", confirm_gender_path,
                            id: "confirm_gender",
                            class: "btn btn-success btn-sm",
                            remote: true,
                            style: "display: none;"
                %>
              <% else %>
                <%= link_to "Подтвердить", confirm_gender_path,
                            id: "confirm_gender",
                            class: "btn btn-success btn-sm",
                            remote: true
                %>
              <% end %>
              <%= link_to "Обновить", update_gender_path,
                          id: "update_gender",
                          class: "btn btn-warning btn-sm",
                          remote: true
              %>
            </div>
          </div>

        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <p>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          </p>
          <p>
            <%= link_to "Home", root_path %>
          </p>
        </div>
      </div>
    </div>
  </div>


<% else %>
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Сервис автоматического определения пола пользователя</h1>
      <p>
        <%= link_to "Sign in", user_session_path, class: "btn btn-primary my-2" %>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-light my-2" %>
      </p>
    </div>
  </section>

<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>